import { SlopRule } from '../core/types';

export const DEFAULT_RULES: readonly SlopRule[] = [
  // 1. Contrast patterns
  {
    id: 'contrast-not-just',
    name: 'Not Just X, It’s Y',
    description: 'Matches the formulaic "It\'s not just X, it\'s Y" rhetorical trope.',
    category: 'contrast',
    pattern:
      "\\b(?:it['’]?s|it is|this is|that is)\\s+not\\s+(?:just|only|simply|merely)\\b",
    flags: 'i',
    examples: [
      "It's not just a tool, it's a revolution.",
      'This is not only a feature, but a mindset.',
      'It is not merely an update.',
    ],
    counterExamples: ['It is not working today.', 'This is not finished yet.'],
    severity: 4,
    weight: 4,
    enabledByDefault: true,
    source: 'builtin',
    versionAdded: '0.1.0',
  },
  {
    id: 'contrast-isnt-just',
    name: 'X Isn’t Just Y',
    description: 'Matches "isn\'t just / wasn\'t merely" contrast assertions.',
    category: 'contrast',
    pattern:
      "\\b(?:isn['’]?t|aren['’]?t|wasn['’]?t|weren['’]?t)\\s+(?:just|only|simply|merely)\\b",
    flags: 'i',
    examples: [
      'AI isn’t just automation.',
      'Leadership isn’t merely about managing people.',
      'These weren’t only quick fixes.',
    ],
    counterExamples: [
      'It isn’t ready for release.',
      'They aren’t coming to the meeting.',
    ],
    severity: 4,
    weight: 4,
    enabledByDefault: true,
    source: 'builtin',
    versionAdded: '0.1.0',
  },
  {
    id: 'contrast-not-only-but',
    name: 'Not Only X But Also Y',
    description: 'Matches expansive "not only... but (also)" bipartite phrasing.',
    category: 'contrast',
    pattern: '\\bnot\\s+only\\b.{1,140}?\\bbut\\s+(?:also\\s+)?',
    flags: 'i',
    examples: [
      'Not only did the team ship on time, but they also exceeded every KPI.',
      'Our platform is not only fast, but reliable.',
    ],
    counterExamples: [
      'Not only three people showed up at the event.',
      'Only authorized users may access the cluster.',
    ],
    severity: 4,
    weight: 4,
    enabledByDefault: true,
    source: 'builtin',
    versionAdded: '0.1.0',
  },
  {
    id: 'contrast-negate-assert',
    name: 'Negate Then Assert (It’s Not X. It’s Y)',
    description: 'Matches short negation sentence followed by immediate re-assertion.',
    category: 'contrast',
    pattern:
      "\\b(?:it['’]?s|it is|this is|that is)\\s+not\\b[^.!?\\n]{1,120}[.!?]\\s*(?:it['’]?s|it is|this is|that is)\\b",
    flags: 'i',
    examples: [
      "It's not about technology. It's about people.",
      'This is not a bug. This is an opportunity.',
      'That is not marketing. That is leadership.',
    ],
    counterExamples: [
      "It's not cold outside. The sun is shining brightly.",
      'This is not required for the test.',
    ],
    severity: 4,
    weight: 4,
    enabledByDefault: true,
    source: 'builtin',
    versionAdded: '0.1.0',
  },
  {
    id: 'contrast-question-isnt',
    name: 'The Question Isn’t X',
    description:
      'Matches "The question / issue / challenge isn\'t whether..." constructions.',
    category: 'contrast',
    pattern:
      "\\b(?:the\\s+)?(?:question|issue|problem|challenge)\\s+(?:isn['’]?t|is\\s+not)\\b",
    flags: 'i',
    examples: [
      'The question isn’t whether AI will replace jobs.',
      'The issue is not how fast we grow.',
      'Our challenge isn’t finding talent.',
    ],
    counterExamples: [
      'The question is whether we can finish today.',
      'An unresolved issue is currently being reviewed.',
    ],
    severity: 4,
    weight: 4,
    enabledByDefault: true,
    source: 'builtin',
    versionAdded: '0.1.0',
  },
  {
    id: 'contrast-more-than-just',
    name: 'More Than Just X',
    description: 'Matches "More than just / simply / merely" framing.',
    category: 'contrast',
    pattern: '\\bmore\\s+than\\s+(?:just|simply|merely)\\b',
    flags: 'i',
    examples: [
      'This is more than just a software tool.',
      'It became more than simply a project.',
    ],
    counterExamples: [
      'He worked more than twenty hours this weekend.',
      'There were more than five people in the room.',
    ],
    severity: 3,
    weight: 3,
    enabledByDefault: true,
    source: 'builtin',
    versionAdded: '0.1.0',
  },

  // 2. Canned openers & declarations
  {
    id: 'opener-answer-simple',
    name: 'The Answer Is Simple',
    description: 'Matches "The answer/solution/truth is simple:" declaration.',
    category: 'canned-opener',
    pattern:
      '\\b(?:the\\s+)?(?:answer|solution|truth|reality|reason)\\s+is\\s+(?:simple|clear|straightforward)\\s*:',
    flags: 'i',
    examples: [
      'The answer is simple: focus on customer trust.',
      'The solution is clear: build with empathy.',
    ],
    counterExamples: ['The answer is 42.', 'The solution is being tested right now.'],
    severity: 3,
    weight: 3,
    enabledByDefault: true,
    source: 'builtin',
    versionAdded: '0.1.0',
  },
  {
    id: 'opener-its-simple',
    name: 'It’s Simple:',
    description: 'Matches colon-prefixed "It\'s simple:".',
    category: 'canned-opener',
    pattern: "\\b(?:it['’]?s|it is)\\s+(?:simple|clear|straightforward)\\s*:",
    flags: 'i',
    examples: [
      "It's simple: prioritize the core workflow.",
      'It is clear: we must act now.',
    ],
    counterExamples: [
      'It is simple to configure this repository.',
      'The simple solution worked.',
    ],
    severity: 3,
    weight: 3,
    enabledByDefault: true,
    source: 'builtin',
    versionAdded: '0.1.0',
  },
  {
    id: 'opener-heres-the-thing',
    name: 'Here’s The Thing',
    description: 'Matches conversational "Here\'s the thing" lead-in.',
    category: 'canned-opener',
    pattern: "\\b(?:but\\s+)?here['’]?s\\s+the\\s+thing\\b",
    flags: 'i',
    examples: [
      "Here's the thing about modern AI development.",
      "But here's the thing: nobody expected this.",
    ],
    counterExamples: ['Here is the item you requested.', 'Put that thing over here.'],
    severity: 3,
    weight: 3,
    enabledByDefault: true,
    source: 'builtin',
    versionAdded: '0.1.0',
  },
  {
    id: 'opener-heres-what-you-need',
    name: 'Here’s What You Need To Know',
    description: 'Matches "Here\'s what you need to know / what matters".',
    category: 'canned-opener',
    pattern:
      "\\bhere['’]?s\\s+what\\s+(?:you\\s+need\\s+to\\s+know|matters|you\\s+should\\s+know)\\b",
    flags: 'i',
    examples: [
      "Here's what you need to know before 2026.",
      "Here's what matters in prompt engineering.",
    ],
    counterExamples: ["Here's what I bought yesterday.", 'What you need is rest.'],
    severity: 3,
    weight: 3,
    enabledByDefault: true,
    source: 'builtin',
    versionAdded: '0.1.0',
  },
  {
    id: 'opener-honest-catch',
    name: 'Here’s The Honest Catch',
    description: 'Matches canned caveat lead-ins such as "Here’s the honest catch:".',
    category: 'canned-opener',
    pattern:
      "\\b(?:but\\s+)?here['’]?s\\s+(?:the\\s+)?(?:honest|real|truthful)\\s+(?:catch|caveat|part)\\b",
    flags: 'i',
    examples: [
      "Here's the honest catch: the model still lacks world knowledge.",
      "But here's the real caveat: deployment takes preparation.",
    ],
    counterExamples: [
      'We caught an honest mistake during the review.',
      'The real caveat was documented in the contract.',
    ],
    severity: 3,
    weight: 3,
    enabledByDefault: true,
    source: 'builtin',
    versionAdded: '0.1.0',
  },
  {
    id: 'opener-let-me-be-clear',
    name: 'Let Me Be Clear',
    description: 'Matches "Let me be clear / Let\'s be clear".',
    category: 'canned-opener',
    pattern: "\\blet(?:\\s+me|['’]s)\\s+be\\s+clear\\b",
    flags: 'i',
    examples: [
      'Let me be clear: this is not about hype.',
      "Let's be clear about what happened.",
    ],
    counterExamples: [
      'The instructions should be clear and concise.',
      'Let them finish the presentation.',
    ],
    severity: 3,
    weight: 3,
    enabledByDefault: true,
    source: 'builtin',
    versionAdded: '0.1.0',
  },
  {
    id: 'opener-hard-truth',
    name: 'The Hard Truth',
    description: 'Matches "The hard/uncomfortable truth" hook.',
    category: 'canned-opener',
    pattern: "\\b(?:the|here['’]?s\\s+the)\\s+(?:hard|uncomfortable|simple)\\s+truth\\b",
    flags: 'i',
    examples: [
      'The uncomfortable truth is most startups fail.',
      "Here's the hard truth about leadership.",
    ],
    counterExamples: [
      'It was a hard exam to pass.',
      'Speaking the truth is always valued.',
    ],
    severity: 3,
    weight: 3,
    enabledByDefault: true,
    source: 'builtin',
    versionAdded: '0.1.0',
  },

  // 3. Faux insight
  {
    id: 'insight-what-most-get-wrong',
    name: 'What Most People Get Wrong',
    description:
      'Matches faux-insider "What most people get wrong / The part everyone misses".',
    category: 'faux-insight',
    pattern:
      '\\b(?:what|the\\s+(?:part|thing))\\s+(?:most\\s+people|everyone|nobody)\\s+(?:get(?:s)?\\s+wrong|miss(?:es)?|talks?\\s+about)\\b',
    flags: 'i',
    examples: [
      'What most people get wrong about remote work is productivity.',
      'The part everyone misses is the incentive structure.',
    ],
    counterExamples: [
      'Most people attended the morning session.',
      'Everyone contributed to the discussion.',
    ],
    severity: 3,
    weight: 3,
    enabledByDefault: true,
    source: 'builtin',
    versionAdded: '0.1.0',
  },
  {
    id: 'insight-nobody-tells-you',
    name: 'What Nobody Tells You',
    description: 'Matches "Here\'s what nobody tells you" secret-revealing opener.',
    category: 'faux-insight',
    pattern:
      "\\b(?:what|here['’]?s\\s+what)\\s+nobody\\s+(?:tells?\\s+you|talks?\\s+about|mentions?)\\b",
    flags: 'i',
    examples: [
      "Here's what nobody tells you about being a founder.",
      'What nobody talks about in tech hiring.',
    ],
    counterExamples: ['Nobody arrived late today.', 'He mentioned the project timeline.'],
    severity: 3,
    weight: 3,
    enabledByDefault: true,
    source: 'builtin',
    versionAdded: '0.1.0',
  },

  // 4. Canned exploration language
  {
    id: 'explore-delve-dive-unpack',
    name: 'Let’s Delve / Dive / Unpack',
    description:
      'Matches formulaic "Let\'s delve into / let\'s unpack this" exploration cues.',
    category: 'canned-exploration',
    pattern:
      "\\blet['’]?s\\s+(?:delve|dive|unpack|explore|take\\s+a\\s+closer\\s+look)\\b",
    flags: 'i',
    examples: [
      "Let's delve into the architectural changes.",
      "Let's unpack this step by step.",
      "Let's dive into why this matters.",
    ],
    counterExamples: ["Let's meet at noon.", 'They decided to explore other options.'],
    severity: 3,
    weight: 3,
    enabledByDefault: true,
    source: 'builtin',
    versionAdded: '0.1.0',
  },

  // 5. Throat-clearing
  {
    id: 'throat-important-to-note',
    name: 'It’s Important To Note',
    description: 'Matches "It is important to note / crucial to understand" filler.',
    category: 'throat-clearing',
    pattern:
      "\\b(?:it\\s+is|it['’]s)\\s+(?:important|crucial|worthwhile|worth)\\s+(?:to\\s+)?(?:note|noting|remember|understand|recognize|highlight)\\b",
    flags: 'i',
    examples: [
      "It's important to note that performance varies.",
      'It is crucial to understand the trade-offs.',
      "It's worth noting the edge cases.",
    ],
    counterExamples: [
      'Please note our new address.',
      'An important milestone was achieved.',
    ],
    severity: 2,
    weight: 2,
    enabledByDefault: true,
    source: 'builtin',
    versionAdded: '0.1.0',
  },
  {
    id: 'throat-at-its-core',
    name: 'At Its Core',
    description: 'Matches "At its core / At the core of this".',
    category: 'throat-clearing',
    pattern: '\\bat\\s+(?:its|the)\\s+core\\b',
    flags: 'i',
    examples: [
      'At its core, engineering is problem solving.',
      'At the core of every great product is simplicity.',
    ],
    counterExamples: ['The CPU has eight cores.', 'He ate the apple down to the core.'],
    severity: 2,
    weight: 2,
    enabledByDefault: true,
    source: 'builtin',
    versionAdded: '0.1.0',
  },
  {
    id: 'throat-in-essence',
    name: 'In Essence',
    description: 'Matches "In essence," transition filler.',
    category: 'throat-clearing',
    pattern: '\\bin\\s+essence\\b',
    flags: 'i',
    examples: [
      'In essence, we are transforming workflow automation.',
      'The proposal is, in essence, a complete rewrite.',
    ],
    counterExamples: [
      'The essence of vanilla is used in baking.',
      'Time is of the essence.',
    ],
    severity: 2,
    weight: 2,
    enabledByDefault: true,
    source: 'builtin',
    versionAdded: '0.1.0',
  },

  // 6. Generic world / landscape language
  {
    id: 'world-fast-paced',
    name: 'In Today’s Fast-Paced World',
    description:
      'Matches "In today\'s fast-paced world / digital age / rapidly changing landscape".',
    category: 'generic-world',
    pattern:
      "\\bin\\s+today['’]?s\\s+(?:fast[- ]paced|digital|rapidly\\s+changing|competitive)\\s+(?:world|age|landscape|environment)\\b",
    flags: 'i',
    examples: [
      "In today's fast-paced world, speed is everything.",
      "In today's digital age, privacy matters.",
      "In today's rapidly changing landscape of tech.",
    ],
    counterExamples: [
      "Today's release includes three bug fixes.",
      'The digital clock on my desk stopped working.',
    ],
    severity: 3,
    weight: 3,
    enabledByDefault: true,
    source: 'builtin',
    versionAdded: '0.1.0',
  },
  {
    id: 'world-ever-evolving',
    name: 'Ever-Evolving Landscape',
    description: 'Matches "ever-evolving landscape / rapidly evolving ecosystem".',
    category: 'generic-world',
    pattern:
      '\\b(?:ever[- ]evolving|rapidly[- ]evolving|constantly[- ]changing)\\s+(?:landscape|world|environment|ecosystem)\\b',
    flags: 'i',
    examples: [
      'In the ever-evolving landscape of artificial intelligence.',
      'Navigating a constantly-changing ecosystem.',
    ],
    counterExamples: [
      'The landscape architecture was beautifully designed.',
      'Species evolve over millions of years.',
    ],
    severity: 3,
    weight: 3,
    enabledByDefault: true,
    source: 'builtin',
    versionAdded: '0.1.0',
  },
  {
    id: 'world-imagine-world',
    name: 'Imagine A World Where',
    description: 'Matches rhetorical "Imagine a world where..." scenario hook.',
    category: 'generic-world',
    pattern: '\\bimagine\\s+(?:a\\s+)?world\\s+where\\b',
    flags: 'i',
    examples: [
      'Imagine a world where manual testing is obsolete.',
      'Imagine world where code writes itself.',
    ],
    counterExamples: [
      'I cannot imagine doing that again.',
      'The world population continues to grow.',
    ],
    severity: 3,
    weight: 2.5,
    enabledByDefault: true,
    source: 'builtin',
    versionAdded: '0.1.0',
  },
  {
    id: 'world-picture-this',
    name: 'Picture This:',
    description: 'Matches storytelling hook "Picture this:".',
    category: 'generic-world',
    pattern: '\\bpicture\\s+this\\s*:',
    flags: 'i',
    examples: ['Picture this: you deploy to production on Friday with zero stress.'],
    counterExamples: [
      'Take a picture of this whiteboard.',
      'Look at this picture carefully.',
    ],
    severity: 3,
    weight: 2.5,
    enabledByDefault: true,
    source: 'builtin',
    versionAdded: '0.1.0',
  },
  {
    id: 'world-in-a-world-where',
    name: 'In A World Where',
    description: 'Matches dramatic movie-trailer style "In a world where...".',
    category: 'generic-world',
    pattern: '\\bin\\s+a\\s+world\\s+where\\b',
    flags: 'i',
    examples: ['In a world where attention spans are shrinking, concise writing wins.'],
    counterExamples: ['He traveled across the world where he met mentors.'],
    severity: 3,
    weight: 2.5,
    enabledByDefault: true,
    source: 'builtin',
    versionAdded: '0.1.0',
  },

  // 7. Dramatic reveal
  {
    id: 'reveal-colon-headline',
    name: 'Dramatic Colon Reveal',
    description:
      'Matches line-starting dramatic reveals: "The answer:", "The result:", "The best part:".',
    category: 'dramatic-reveal',
    pattern:
      '^(?:the\\s+)?(?:answer|reason|result|reality|truth|best\\s+part|problem|solution|takeaway)\\s*(?:is)?\\s*:\\s*\\S+',
    flags: 'im',
    examples: [
      'The answer: automated workflows.',
      'The best part: it works out of the box.',
      'The result: 10x developer velocity.',
    ],
    counterExamples: [
      'Please submit your answer before the deadline.',
      'He reached a favorable result.',
    ],
    severity: 3,
    weight: 3,
    enabledByDefault: true,
    source: 'builtin',
    versionAdded: '0.1.0',
  },
  {
    id: 'reveal-rhetorical-question',
    name: 'Rhetorical Question Reveal',
    description:
      'Matches "The result? Transformation." / "The reason? Simplicity." syntax.',
    category: 'dramatic-reveal',
    pattern: '\\b(?:the\\s+)?(?:result|reason|answer|solution|benefit)\\?\\s+\\S+',
    flags: 'i',
    examples: [
      'The result? Scalable growth.',
      'The reason? Pure simplicity.',
      'The answer? Consistency.',
    ],
    counterExamples: [
      'Did you get the test result?',
      'What was the reason for the delay?',
    ],
    severity: 3,
    weight: 3,
    enabledByDefault: true,
    source: 'builtin',
    versionAdded: '0.1.0',
  },

  // 8. Generic bridge phrases
  {
    id: 'bridge-where-x-comes-in',
    name: 'This Is Where X Comes In',
    description: 'Matches "This is where [Tool/AI/Strategy] comes in".',
    category: 'generic-bridge',
    pattern: '\\bthis\\s+is\\s+where\\b[^.!?\\n]{1,100}\\bcomes?\\s+in\\b',
    flags: 'i',
    examples: [
      'This is where our new framework comes in.',
      'This is where intelligent caching comes in to save latency.',
    ],
    counterExamples: ['This is where the train arrives.', "He comes in at nine o'clock."],
    severity: 2,
    weight: 2,
    enabledByDefault: true,
    source: 'builtin',
    versionAdded: '0.1.0',
  },
  {
    id: 'bridge-when-it-comes-to',
    name: 'When It Comes To',
    description: 'Matches filler phrase "When it comes to X".',
    category: 'generic-bridge',
    pattern: '\\bwhen\\s+it\\s+comes\\s+to\\b',
    flags: 'i',
    examples: ['When it comes to cloud architecture, simplicity always wins.'],
    counterExamples: ['Let me know when it arrives.', 'The package comes to your door.'],
    severity: 2,
    weight: 1.5,
    enabledByDefault: true,
    source: 'builtin',
    versionAdded: '0.1.0',
  },
  {
    id: 'bridge-oversignposting',
    name: 'Over-Signposting Bridges',
    description: 'Matches "That being said", "With that in mind", "Having said that".',
    category: 'generic-bridge',
    pattern:
      '\\b(?:that\\s+being\\s+said|with\\s+that\\s+in\\s+mind|having\\s+said\\s+that)\\b',
    flags: 'i',
    examples: [
      'That being said, we must maintain rigor.',
      'With that in mind, let us review the metrics.',
      'Having said that, caution is warranted.',
    ],
    counterExamples: ['He said that yesterday.', 'Keep that in your notebook.'],
    severity: 2,
    weight: 1.5,
    enabledByDefault: true,
    source: 'builtin',
    versionAdded: '0.1.0',
  },
  {
    id: 'bridge-formal-glue',
    name: 'Formal Glue Transitions',
    description:
      'Matches sentence-starting "Moreover,", "Furthermore,", "Additionally,".',
    category: 'generic-bridge',
    pattern: '^(?:moreover|furthermore|additionally|consequently|nevertheless)\\s*,',
    flags: 'im',
    examples: [
      'Furthermore, the architecture reduces memory overhead.',
      'Additionally, all unit tests passed.',
    ],
    counterExamples: [
      'We will add additionally requested properties.',
      'Never say never.',
    ],
    severity: 1,
    weight: 1,
    enabledByDefault: true,
    source: 'builtin',
    versionAdded: '0.1.0',
  },
  {
    id: 'bridge-contrived-concession',
    name: 'Contrived Concession (While X May Seem...)',
    description: 'Matches "While this may seem simple, in reality..." symmetry.',
    category: 'generic-bridge',
    pattern:
      '\\bwhile\\b[^.!?\\n]{1,120}\\b(?:may|might|can)\\s+(?:seem|appear)\\b[^.!?\\n]{0,100},\\s*(?:in\\s+reality|actually|however)\\b',
    flags: 'i',
    examples: [
      'While this might seem straightforward, in reality it is complex.',
      'While this can appear trivial, actually it requires deep planning.',
    ],
    counterExamples: ['While waiting for the build, I wrote documentation.'],
    severity: 2,
    weight: 2,
    enabledByDefault: true,
    source: 'builtin',
    versionAdded: '0.1.0',
  },
  {
    id: 'bridge-benefits-challenges',
    name: 'Benefits And Challenges Symmetry',
    description:
      'Matches balanced "While X offers benefits, it presents challenges" hedging.',
    category: 'generic-bridge',
    pattern:
      '\\bwhile\\b[^.!?\\n]{0,140}\\b(?:benefits?|advantages?|opportunities?)\\b[^.!?\\n]{0,140}\\b(?:challenges?|drawbacks?|risks?)\\b',
    flags: 'i',
    examples: [
      'While microservices offer great benefits, they introduce architectural challenges.',
      'While this offers advantages, we must evaluate the risks.',
    ],
    counterExamples: [
      'The team embraced challenges with confidence.',
      'We listed benefits of the new platform.',
    ],
    severity: 2,
    weight: 2,
    enabledByDefault: true,
    source: 'builtin',
    versionAdded: '0.1.0',
  },

  // 9. Inflated metaphor / business language
  {
    id: 'metaphor-testament-to',
    name: 'Testament To',
    description: 'Matches "Stands as a testament to innovation".',
    category: 'inflated-metaphor',
    pattern:
      '\\b(?:stand|stands|stood|serve|serves|served)\\s+as\\s+(?:a\\s+)?testament\\s+to\\b',
    flags: 'i',
    examples: [
      'Our team’s resilience stands as a testament to our culture.',
      'This milestone serves as a testament to our hard work.',
    ],
    counterExamples: [
      'He wrote a last will and testament.',
      'The witness testified in court.',
    ],
    severity: 3,
    weight: 3,
    enabledByDefault: true,
    source: 'builtin',
    versionAdded: '0.1.0',
  },
  {
    id: 'metaphor-navigate-complexities',
    name: 'Navigate The Complexities',
    description: 'Matches "Navigate the complexities / challenges / landscape".',
    category: 'inflated-metaphor',
    pattern:
      '\\bnavigat(?:e|es|ed|ing)\\s+(?:the\\s+)?(?:complexities|challenges|landscape|intricacies)\\s+of\\b',
    flags: 'i',
    examples: [
      'Helping enterprises navigate the complexities of digital transformation.',
      'Navigating the landscape of regulatory compliance.',
    ],
    counterExamples: [
      'Navigate to the settings page in your browser.',
      'The ship navigated through the narrow canal.',
    ],
    severity: 3,
    weight: 3,
    enabledByDefault: true,
    source: 'builtin',
    versionAdded: '0.1.0',
  },
  {
    id: 'metaphor-tapestry',
    name: 'Tapestry Metaphor',
    description: 'Matches "rich/intricate tapestry of..." metaphors.',
    category: 'inflated-metaphor',
    pattern: '\\b(?:rich|complex|intricate|vibrant)?\\s*tapestry\\s+of\\b',
    flags: 'i',
    examples: [
      'Creating a rich tapestry of experiences.',
      'A complex tapestry of modern microservices.',
    ],
    counterExamples: ['The medieval tapestry hung on the museum wall.'],
    severity: 3,
    weight: 3,
    enabledByDefault: true,
    source: 'builtin',
    versionAdded: '0.1.0',
  },
  {
    id: 'metaphor-pave-the-way',
    name: 'Pave The Way',
    description: 'Matches "Paves the way for future innovation".',
    category: 'inflated-metaphor',
    pattern: '\\bpav(?:e|es|ed|ing)\\s+the\\s+way\\s+for\\b',
    flags: 'i',
    examples: [
      'Paving the way for next-generation intelligence.',
      'This discovery paves the way for sustainable energy.',
    ],
    counterExamples: ['The city paved the asphalt road yesterday.'],
    severity: 3,
    weight: 2.5,
    enabledByDefault: true,
    source: 'builtin',
    versionAdded: '0.1.0',
  },
  {
    id: 'metaphor-shed-light',
    name: 'Shed Light On',
    description: 'Matches "Sheds light on key insights".',
    category: 'inflated-metaphor',
    pattern: '\\bshed(?:s|ding)?\\s+light\\s+on\\b',
    flags: 'i',
    examples: [
      'This research sheds light on user retention.',
      'Shedding light on the underlying bottlenecks.',
    ],
    counterExamples: [
      'We stored the tools inside the garden shed.',
      'Turn on the overhead light.',
    ],
    severity: 2,
    weight: 2,
    enabledByDefault: true,
    source: 'builtin',
    versionAdded: '0.1.0',
  },
  {
    id: 'metaphor-pivotal-role',
    name: 'Plays A Pivotal Role',
    description: 'Matches "Plays a pivotal / crucial / critical role in...".',
    category: 'inflated-metaphor',
    pattern:
      '\\b(?:play|plays|played|playing)\\s+(?:a\\s+)?(?:crucial|critical|pivotal|vital|significant|key)\\s+role\\s+in\\b',
    flags: 'i',
    examples: [
      'AI plays a pivotal role in optimizing logistics.',
      'Community plays a crucial role in product adoption.',
    ],
    counterExamples: [
      'The actor played Hamlet on stage.',
      'Children were playing in the park.',
    ],
    severity: 3,
    weight: 3,
    enabledByDefault: true,
    source: 'builtin',
    versionAdded: '0.1.0',
  },
  {
    id: 'metaphor-unlock-power',
    name: 'Unlock The Power / Potential',
    description: 'Matches "Unlock the power / potential of X".',
    category: 'inflated-metaphor',
    pattern:
      '\\bunlock(?:s|ed|ing)?\\s+(?:the\\s+)?(?:full\\s+|true\\s+)?(?:power|potential|possibilities|value)\\b',
    flags: 'i',
    examples: [
      'Unlock the power of your engineering data.',
      'Unlocking the full potential of your workforce.',
    ],
    counterExamples: ['Unlock the front door with your key.'],
    severity: 3,
    weight: 3,
    enabledByDefault: true,
    source: 'builtin',
    versionAdded: '0.1.0',
  },
  {
    id: 'metaphor-new-era',
    name: 'Ushering In A New Era',
    description: 'Matches "Ushering in a new era / Marks a new era".',
    category: 'inflated-metaphor',
    pattern:
      '\\b(?:usher(?:s|ed|ing)?\\s+in|mark(?:s|ed|ing)?)\\s+(?:a\\s+)?new\\s+era\\b',
    flags: 'i',
    examples: [
      'Ushering in a new era of decentralized finance.',
      'This launch marks a new era in software engineering.',
    ],
    counterExamples: ['The usher showed us to our seats at the theater.'],
    severity: 3,
    weight: 2.5,
    enabledByDefault: true,
    source: 'builtin',
    versionAdded: '0.1.0',
  },
  {
    id: 'metaphor-revolutionize',
    name: 'Revolutionize / Game Changer',
    description: 'Matches hyperbole terms "revolutionizing" and "game changer".',
    category: 'inflated-metaphor',
    pattern: '\\b(?:revolutioniz(?:e|es|ed|ing)|game[- ]changer)\\b',
    flags: 'i',
    examples: [
      'A true game-changer for cloud operations.',
      'Revolutionizing the way teams collaborate.',
    ],
    counterExamples: [
      'The industrial revolution began in the 18th century.',
      'The board game had multiple pieces.',
    ],
    severity: 3,
    weight: 2.5,
    enabledByDefault: true,
    source: 'builtin',
    versionAdded: '0.1.0',
  },

  // 10. Common LLM vocabulary
  {
    id: 'llm-vocab-cluster',
    name: 'Classic LLM Vocabulary',
    description:
      'Matches overused LLM adjectives and verbs: delve, underscore, pivotal, nuanced, multifaceted, intricate, meticulous, commendable, seamless, transformative.',
    category: 'llm-vocabulary',
    pattern:
      '\\b(?:delv(?:e|es|ed|ing)|underscore(?:s|d|ing)?|showcas(?:e|es|ed|ing)|pivotal|nuanced|multifaceted|intricate|meticulous|commendable|seamless|transformative)\\b',
    flags: 'i',
    examples: [
      'This transformative shift highlights a nuanced perspective.',
      'We delve into the intricate architecture.',
      'A commendable effort to showcase seamless integration.',
    ],
    counterExamples: [
      'The team completed the project on schedule.',
      'The database query returned within five milliseconds.',
    ],
    severity: 2,
    weight: 2,
    enabledByDefault: true,
    source: 'builtin',
    versionAdded: '0.1.0',
  },

  // 11. Corporate inflation
  {
    id: 'corp-inflation-cluster',
    name: 'Corporate Inflation',
    description:
      'Matches buzzwords: leverage, utilize, facilitate, empower, foster, robust.',
    category: 'corporate-language',
    pattern:
      '\\b(?:leverag(?:e|es|ed|ing)|utiliz(?:e|es|ed|ing)|facilitat(?:e|es|ed|ing)|empower(?:s|ed|ing)?|foster(?:s|ed|ing)?|robust)\\b',
    flags: 'i',
    examples: [
      'We leverage synergies to empower our workforce and foster collaboration.',
      'Utilizing a robust infrastructure to facilitate growth.',
    ],
    counterExamples: [
      'We used a screwdriver to fix the desk.',
      'The system is stable and fast.',
    ],
    severity: 1,
    weight: 1,
    enabledByDefault: true,
    source: 'builtin',
    versionAdded: '0.1.0',
  },

  // 12. Empty intensifiers & vague quantifiers
  {
    id: 'intensifier-empty-cluster',
    name: 'Empty Intensifiers',
    description:
      'Matches rhetorical intensifiers: absolutely, fundamentally, incredibly, remarkably, undoubtedly.',
    category: 'empty-intensifier',
    pattern:
      '\\b(?:absolutely|certainly|clearly|definitely|essentially|fundamentally|incredibly|remarkably|significantly|truly|undoubtedly)\\b',
    flags: 'i',
    examples: [
      'This is fundamentally transformative and truly incredible.',
      'It undoubtedly represents a remarkably significant breakthrough.',
    ],
    counterExamples: [
      'The result is verified by empirical measurement.',
      'The test passed without warnings.',
    ],
    severity: 1,
    weight: 1,
    enabledByDefault: true,
    source: 'builtin',
    versionAdded: '0.1.0',
  },
  {
    id: 'quantifier-vague',
    name: 'Vague Quantities',
    description: 'Matches non-specific quantifiers: various, numerous, a wide range of.',
    category: 'empty-intensifier',
    pattern:
      '\\b(?:various|numerous|several|a\\s+(?:wide\\s+)?range\\s+of|a\\s+variety\\s+of)\\b',
    flags: 'i',
    examples: [
      'Across various domains and numerous enterprise sectors.',
      'Supporting a wide range of bespoke solutions.',
    ],
    counterExamples: [
      'Exactly 47 customers responded to the survey.',
      'We tested five distinct browsers.',
    ],
    severity: 1,
    weight: 1,
    enabledByDefault: true,
    source: 'builtin',
    versionAdded: '0.1.0',
  },

  // 13. Unsupported authority
  {
    id: 'authority-unattributed',
    name: 'Unattributed Authority Claims',
    description:
      'Matches unreferenced "Studies show", "Research suggests", "Experts agree".',
    category: 'unsupported-authority',
    pattern:
      '\\b(?:studies|research|experts|industry\\s+leaders|data)\\s+(?:show|shows|suggest|suggests|indicate|indicates|reveal|reveals|agree)\\b',
    flags: 'i',
    examples: [
      'Studies show that engaged employees are more productive.',
      'Industry leaders agree that continuous learning is critical.',
      'Research suggests remote workers save commute hours.',
    ],
    counterExamples: [
      'Professor Smith published verified laboratory findings in Nature.',
      'Dr. Alvarez presented her findings at the conference.',
    ],
    severity: 3,
    weight: 2.5,
    enabledByDefault: true,
    source: 'builtin',
    versionAdded: '0.1.0',
  },

  // 14. Canned conclusions
  {
    id: 'conclusion-canned-summary',
    name: 'Canned Conclusion Hook',
    description:
      'Matches generic conclusion headers "In conclusion", "To sum up", "In summary".',
    category: 'canned-conclusion',
    pattern: '\\b(?:in\\s+conclusion|to\\s+sum\\s+up|in\\s+summary|in\\s+closing)\\b',
    flags: 'i',
    examples: [
      'In conclusion, leadership is a journey, not a destination.',
      'To sum up: invest in your people first.',
    ],
    counterExamples: [
      'We reached a final conclusion after the audit.',
      'A summary of the release notes is attached below.',
    ],
    severity: 3,
    weight: 3,
    enabledByDefault: true,
    source: 'builtin',
    versionAdded: '0.1.0',
  },
  {
    id: 'conclusion-ultimately',
    name: '“Ultimately,” Conclusion',
    description: 'Matches line-opening "Ultimately," wrap-up filler.',
    category: 'canned-conclusion',
    pattern: '^\\s*ultimately\\s*,',
    flags: 'im',
    examples: ['Ultimately, the choice comes down to execution.'],
    counterExamples: ['The system will ultimately terminate after timeout.'],
    severity: 3,
    weight: 2.5,
    enabledByDefault: true,
    source: 'builtin',
    versionAdded: '0.1.0',
  },
  {
    id: 'conclusion-all-things-considered',
    name: 'All Things Considered / At The End Of The Day',
    description:
      'Matches folksy wrap-ups "At the end of the day", "All things considered".',
    category: 'canned-conclusion',
    pattern: '\\b(?:all\\s+things\\s+considered|at\\s+the\\s+end\\s+of\\s+the\\s+day)\\b',
    flags: 'i',
    examples: [
      'At the end of the day, quality code speaks for itself.',
      'All things considered, the migration was a triumph.',
    ],
    counterExamples: [
      'We worked until the end of the day.',
      'Considered all factors during the review.',
    ],
    severity: 2,
    weight: 2,
    enabledByDefault: true,
    source: 'builtin',
    versionAdded: '0.1.0',
  },
  {
    id: 'conclusion-future-bright',
    name: 'Bright Future Ending',
    description:
      'Matches optimistic platitudes "The future is bright / looks promising".',
    category: 'canned-conclusion',
    pattern: '\\b(?:the\\s+)?future\\s+(?:is|looks)\\s+(?:bright|promising|exciting)\\b',
    flags: 'i',
    examples: [
      'The future is bright for open source software.',
      'The future looks promising as new capabilities emerge.',
    ],
    counterExamples: [
      'The weather forecast for the future looks sunny.',
      'Bright sunlight illuminated the room.',
    ],
    severity: 3,
    weight: 3,
    enabledByDefault: true,
    source: 'builtin',
    versionAdded: '0.1.0',
  },
  {
    id: 'conclusion-forward-looking',
    name: 'Forward-Looking Filler',
    description: 'Matches "As we move forward / As we look ahead".',
    category: 'canned-conclusion',
    pattern: '\\bas\\s+we\\s+(?:move|look)\\s+(?:forward|ahead)\\b',
    flags: 'i',
    examples: [
      'As we look ahead to Q4 and beyond.',
      'As we move forward, security remains our baseline.',
    ],
    counterExamples: [
      'Please move forward in the queue.',
      'Look ahead when driving on the highway.',
    ],
    severity: 3,
    weight: 2.5,
    enabledByDefault: true,
    source: 'builtin',
    versionAdded: '0.1.0',
  },

  // 15. LinkedIn-style scaffolding
  {
    id: 'scaffold-key-takeaway',
    name: 'Key Takeaway / Bottom Line',
    description:
      'Matches scaffolding markers "The key takeaway is", "The bottom line is".',
    category: 'scaffolding',
    pattern: '\\b(?:the\\s+)?(?:key\\s+takeaway|bottom\\s+line)(?:\\s+is\\b|\\s*:)',
    flags: 'i',
    examples: [
      'The key takeaway is to build with resilience.',
      'The bottom line: test early and test often.',
    ],
    counterExamples: [
      'We ordered takeaway dinner for the team.',
      'Draw a solid bottom line on the diagram.',
    ],
    severity: 3,
    weight: 2.5,
    enabledByDefault: true,
    source: 'builtin',
    versionAdded: '0.1.0',
  },
  {
    id: 'scaffold-beauty-of',
    name: 'The Beauty Of X Is',
    description: 'Matches "The beauty of this approach is...".',
    category: 'scaffolding',
    pattern: '\\bthe\\s+beauty\\s+of\\b[^.!?\\n]{0,100}\\bis\\b',
    flags: 'i',
    examples: [
      'The beauty of TypeScript is compile-time safety.',
      'The beauty of this architecture is zero downtime.',
    ],
    counterExamples: ['The natural beauty of the national park is stunning.'],
    severity: 3,
    weight: 2.5,
    enabledByDefault: true,
    source: 'builtin',
    versionAdded: '0.1.0',
  },
  {
    id: 'scaffold-power-of',
    name: 'The Power Of X Lies In Y',
    description: 'Matches "The power of X lies in...".',
    category: 'scaffolding',
    pattern: '\\bthe\\s+power\\s+of\\b[^.!?\\n]{1,100}\\blies\\s+in\\b',
    flags: 'i',
    examples: [
      'The power of declarative UI lies in predictability.',
      'The power of collaboration lies in diverse perspectives.',
    ],
    counterExamples: ['The power outage lasted twenty minutes.'],
    severity: 2,
    weight: 2,
    enabledByDefault: true,
    source: 'builtin',
    versionAdded: '0.1.0',
  },
  {
    id: 'scaffold-never-more-important',
    name: 'Has Never Been More Important',
    description: 'Matches "X has/have never been more important / critical / essential".',
    category: 'scaffolding',
    pattern:
      '\\b(?:has|have)\\s+never\\s+been\\s+more\\s+(?:important|critical|relevant|essential)\\b',
    flags: 'i',
    examples: [
      'Data integrity has never been more important.',
      'Code reviews have never been more critical.',
    ],
    counterExamples: ['This feature has been tested thoroughly.'],
    severity: 3,
    weight: 2.5,
    enabledByDefault: true,
    source: 'builtin',
    versionAdded: '0.1.0',
  },
  {
    id: 'scaffold-now-more-than-ever',
    name: 'Now More Than Ever',
    description: 'Matches urgency cliché "Now more than ever...".',
    category: 'scaffolding',
    pattern: '\\bnow\\s+more\\s+than\\s+ever\\b',
    flags: 'i',
    examples: ['Now more than ever, engineering leaders must adapt.'],
    counterExamples: [
      'Now is the time to start.',
      'More than ever before, we have options.',
    ],
    severity: 2,
    weight: 2,
    enabledByDefault: true,
    source: 'builtin',
    versionAdded: '0.1.0',
  },
  {
    id: 'scaffold-whether-triad',
    name: 'Whether-You’re Triad',
    description: 'Matches "Whether you\'re a developer, manager, or founder...".',
    category: 'scaffolding',
    pattern: "\\bwhether\\s+you(?:['’]re|\\s+are)\\b[^.!?\\n]{1,180}\\bor\\b",
    flags: 'i',
    examples: [
      'Whether you are an engineer, product manager, or designer, this affects you.',
      "Whether you're starting out or leading a massive team.",
    ],
    counterExamples: ['Check whether you have write permissions.'],
    severity: 2,
    weight: 2,
    enabledByDefault: true,
    source: 'builtin',
    versionAdded: '0.1.0',
  },
  {
    id: 'scaffold-by-doing-x',
    name: 'By Doing X, You Can Y',
    description: 'Matches prescriptive "By embracing X, you can unlock Y".',
    category: 'scaffolding',
    pattern:
      '\\bby\\s+(?!evening\\b|morning\\b)\\w+ing\\b[^.!?\\n]{0,120},\\s+you\\s+can\\b',
    flags: 'i',
    examples: [
      'By adopting automated CI pipelines, you can ship with total confidence.',
      'By focusing on customer empathy, you can build sticky products.',
    ],
    counterExamples: ['By evening, you can collect the parcel.'],
    severity: 2,
    weight: 2,
    enabledByDefault: true,
    source: 'builtin',
    versionAdded: '0.1.0',
  },

  // 16. Formatting & Structural indicators
  {
    id: 'format-chatgpt-bold-bullets',
    name: 'ChatGPT Bold Label Bullets',
    description:
      'Matches LLM-style bullet points with bold prefixes like **Key takeaway:** or **Why it matters:**.',
    category: 'formatting',
    pattern: '^\\s*(?:[-*]\\s+)?\\*\\*[^*\\n]{2,50}:\\*\\*',
    flags: 'm',
    examples: [
      '**Key takeaway:** Focus on sustainable velocity.',
      '* **Why it matters:** Users expect zero latency.',
      '- **Action item:** Refactor legacy queries.',
    ],
    counterExamples: [
      'This text is **bold** but not a colon label header.',
      '* Standard bullet point without bold prefix.',
    ],
    severity: 3,
    weight: 2.5,
    enabledByDefault: true,
    source: 'builtin',
    versionAdded: '0.1.0',
  },
  {
    id: 'structural-rule-of-three',
    name: 'Rule-Of-Three Adjective Lists (Density)',
    description:
      'Matches tricolon / rule-of-three lists like "fast, scalable, and reliable". Only triggers when repeated.',
    category: 'structural',
    pattern: '\\b[\\w-]{2,},\\s+[\\w-]{2,},\\s+(?:and|or)\\s+[\\w-]{2,}\\b',
    flags: 'i',
    examples: [
      'Our new service is fast, scalable, and reliable.',
      'Design software that is simple, powerful, and intuitive.',
    ],
    counterExamples: ['Apples and oranges were on the table.'],
    severity: 1,
    weight: 1,
    isDensityRule: true,
    densityThreshold: 2,
    enabledByDefault: true,
    source: 'builtin',
    versionAdded: '0.1.0',
  },
  {
    id: 'structural-em-dash-spam',
    name: 'Excessive Em-Dash Density',
    description:
      'Detects excessive em-dash usage used for contrived dramatic asides. Triggers above threshold.',
    category: 'structural',
    pattern: '[\\u2014\\u2013]|--',
    flags: 'g',
    examples: [
      'Engineering—real engineering—is not about code—it is about clarity.',
      'The architecture—built on modular principles—scaled seamlessly—every single day.',
    ],
    counterExamples: [
      'The range is from 10 to 20 ms.',
      'Standard punctuation without any dash characters.',
    ],
    severity: 1,
    weight: 0.5,
    isDensityRule: true,
    densityThreshold: 3,
    enabledByDefault: true,
    source: 'builtin',
    versionAdded: '0.1.0',
  },
];
